# npm works with Node.js. Here we get the latest Node.js version. Note that node contains npm 
image: node:20-alpine3.16
  
# before building we need to install the dependencies on the runner and change directory to SonarVisualizer.
before_script:
  - cd SonarVisualizer
  - npm install

# we build the first job which configures dependencies on the Gitlab runner
test-job:
  #we want the the docker runner to execute this as the image can be run on a docker runner only
  tags:
    - docker
  # the commands of script are run on the Gitlab runner which works on Linux OS. We want to run the test files that have been written for the GUI
  script:
    - npm run test
  